theme = "catppuccin_mocha"

[editor]
scrolloff = 10
line-number = "relative"
cursorline = true
color-modes = true
completion-timeout = 50

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[editor.lsp]
display-inlay-hints = true
